var Renderer=function(a){var c=this;this.width;this.height;this.currentPosition=0;this.scale=4;this.offsetY=this.offsetX=0;this.keydown=!1;this.vbo;this.vao;this.ebo;this.maxQuads=16384;this.maxVertices;this.vertices;this.indices;this.indexPtr=this.vertexPtr=this.spriteCount=0;this.focusedOnPlayer=!0;this.lastTime;this.d_t;this.running=!1;this.spritesheet=new Image;this.spritesheet.crossOrigin="";this.spritesheet.src=a;this.spritesheet.addEventListener("load",function(){c.running?c.setTexture(c.spritesheet):
(c.running=!0,c.merge(),c.initWebGl(),c.start(),requestAnimationFrame(function(a){return c.update(a)}))});window.onresize=function(a){MOBILE.is=1200>=window.innerWidth;MOBILE.prev!==MOBILE.is&&MOBILE.switch();MOBILE.prev=MOBILE.is;c.resize()}};
Renderer.prototype.merge=function(){var a=this,c=document.createElement("style");c.styleSheet?c.styleSheet.cssText=stylesSource:c.appendChild(document.createTextNode(stylesSource));document.getElementsByTagName("head")[0].appendChild(c);this.openedDoors=[];var b=ENGINE.applyData;ENGINE.applyData=function(c,e){b(c,e);a.openedDoors=c.doors}};
Renderer.prototype.initWebGl=function(){this.canvas=document.createElement("canvas");this.canvas.id="canvas";this.parent=document.getElementById("world-box");this.parent.style.position="relative";this.parent.insertBefore(this.canvas,null);this.webGl=this.canvas.getContext("webgl2");null===this.webGl?alert("sorry bub, but you should start using a modern browser..."):(this.resize(),this.shader=new Shader(this.webGl),this.shader.compile(vertexShaderSource,fragmentShaderSource),this.shader.compiled?(this.setTexture(this.spritesheet),
this.maxVertices=16*this.maxQuads,this.vertices=new Float32Array(this.maxVertices),this.vbo=this.webGl.createBuffer(),this.webGl.bindBuffer(this.webGl.ARRAY_BUFFER,this.vbo),this.webGl.bufferData(this.webGl.ARRAY_BUFFER,this.vertices,this.webGl.DYNAMIC_DRAW),this.indices=generateIndices(6*this.maxQuads),this.ebo=this.webGl.createBuffer(),this.webGl.bindBuffer(this.webGl.ELEMENT_ARRAY_BUFFER,this.ebo),this.webGl.bufferData(this.webGl.ELEMENT_ARRAY_BUFFER,this.indices,this.webGl.DYNAMIC_DRAW),this.webGl.useProgram(this.shader.programId),
this.webGl.enableVertexAttribArray(this.shader.getAttribute("a_position")),this.webGl.bindBuffer(this.webGl.ARRAY_BUFFER,this.vbo),this.webGl.vertexAttribPointer(this.shader.getAttribute("a_position"),2,this.webGl.FLOAT,!1,16,0),this.webGl.enableVertexAttribArray(this.shader.getAttribute("a_texcoord")),this.webGl.vertexAttribPointer(this.shader.getAttribute("a_texcoord"),2,this.webGl.FLOAT,!1,16,8),this.webGl.bindBuffer(this.webGl.ELEMENT_ARRAY_BUFFER,this.ebo),this.webGl.uniform1i(this.shader.getUniform("u_texture"),
0)):alert("uh oh, spaghetti ohs. i suck at writing shaders"))};
Renderer.prototype.setTexture=function(a){this.textureId||(this.textureId=this.webGl.createTexture(),this.webGl.bindTexture(this.webGl.TEXTURE_2D,this.textureId),this.webGl.texParameteri(this.webGl.TEXTURE_2D,this.webGl.TEXTURE_MIN_FILTER,this.webGl.NEAREST_MIPMAP_NEAREST),this.webGl.texParameteri(this.webGl.TEXTURE_2D,this.webGl.TEXTURE_MIN_FILTER,this.webGl.NEAREST),this.webGl.texParameteri(this.webGl.TEXTURE_2D,this.webGl.TEXTURE_MAG_FILTER,this.webGl.NEAREST),this.webGl.blendFunc(this.webGl.SRC_ALPHA,
this.webGl.ONE_MINUS_SRC_ALPHA),this.webGl.enable(this.webGl.BLEND));this.webGl.texImage2D(this.webGl.TEXTURE_2D,0,this.webGl.RGBA,this.webGl.RGBA,this.webGl.UNSIGNED_BYTE,a)};Renderer.prototype.start=function(){this.moveCamera(YOU.x,YOU.y);this.curX=YOU.x;this.curY=YOU.y};
Renderer.prototype.update=function(a){var c=this;this.d_t=this.lastTime?a-this.lastTime:0;this.lastTime=a;a=this.d_t/500;this.curX=Math.abs(YOU.x-this.curX)<a?YOU.x:this.curX-(this.curX-YOU.x)*a;this.curY=Math.abs(YOU.y-this.curY)<a?YOU.y:this.curY-(this.curY-YOU.y)*a;this.moveCamera(this.curX,this.curY);this.drawScene();requestAnimationFrame(function(a){return c.update(a)})};
Renderer.prototype.moveCamera=function(a,c){this.offsetX=12*a*this.scale-this.canvas.width/2+6*this.scale;this.offsetY=12*c*this.scale-this.canvas.height/2+6*this.scale};Renderer.prototype.resize=function(){this.width=this.parent.clientWidth;this.height=this.parent.clientHeight;this.canvas.width=this.width;this.canvas.height=this.height;this.webGl.viewport(0,0,this.width,this.height)};
Renderer.prototype.drawSprite=function(a,c,b,d){this.vertexPtr>=this.maxVertices&&this.render();var e=b*this.scale,f=d*this.scale;b=(b+1)*this.scale;d=(d+1)*this.scale;var h=a+.01,g=c+.99;a+=.99;c+=.01;this.addAttribute(this.normalizePosition(e,f));this.addAttribute(this.normalizeTexture(h,g));this.addAttribute(this.normalizePosition(e,d));this.addAttribute(this.normalizeTexture(h,c));this.addAttribute(this.normalizePosition(b,f));this.addAttribute(this.normalizeTexture(a,g));this.addAttribute(this.normalizePosition(b,
d));this.addAttribute(this.normalizeTexture(a,c));this.indexPtr+=6};Renderer.prototype.render=function(){this.webGl.bufferSubData(this.webGl.ARRAY_BUFFER,0,this.vertices,0,this.vertexPtr);this.webGl.drawElements(this.webGl.TRIANGLES,this.indexPtr,this.webGl.UNSIGNED_SHORT,0);this.vertexPtr=this.indexPtr=0};Renderer.prototype.addAttribute=function(a){this.vertices[this.vertexPtr++]=a.x;this.vertices[this.vertexPtr++]=a.y};
Renderer.prototype.normalizePosition=function(a,c){return{x:Math.floor(12*a-this.offsetX)/this.width*2-1,y:Math.floor(12*c-this.offsetY)/this.height*2-1}};Renderer.prototype.normalizeTexture=function(a,c){return{x:16*a/this.spritesheet.width,y:16*c/this.spritesheet.height}};
Renderer.prototype.drawScene=function(){this.webGl.clearColor(0,0,0,0);this.webGl.clear(this.webGl.COLOR_BUFFER_BIT);this.scale=this.canvas.height/30/12;for(var a=YOU.x,c=YOU.y,b=a-18;b<a+18;b++)for(var d=c-18;d<c+18;d++)switch(WORLD.deriveTile(b,d)){case WORLD.TILES.sand:this.drawSprite(1,0,b,d);break;case WORLD.TILES.grass:dynamicTile(this,WORLD.TILES.grass,4,3,b,d);break;case WORLD.TILES.tree:.57<WORLD.getPerlin(b,d+5500,1E4)?this.drawSprite(2,1,b,d):this.drawSprite(1,1,b,d);break;case WORLD.TILES.mountain:dynamicTile(this,
WORLD.TILES.mountain,0,3,b,d,!0);break;case WORLD.TILES.swamp:dynamicTile(this,WORLD.TILES.swamp,12,3,b,d);break;case WORLD.TILES.forest:dynamicTile(this,WORLD.TILES.forest,8,3,b,d);break;case WORLD.TILES.water:dynamicTile(this,WORLD.TILES.water,16,3,b,d);break;case WORLD.TILES.island:this.drawSprite(2,0,b,d);break;case WORLD.TILES.worldedge:dynamicTile(this,WORLD.TILES.worldedge,20,3,b,d);break;case WORLD.TILES.house:this.drawSprite(3,1,b,d);break;case WORLD.TILES.city:this.drawSprite(4,1,b,d);break;
case WORLD.TILES.startbox:this.drawSprite(5,1,b,d);break;default:this.drawSprite(0,0,b,d)}for(a=0;a<WORLD.otherStumps.length;a++)c=WORLD.otherStumps[a],.57<WORLD.getPerlin(c.x,c.y+5500,1E4)?this.drawSprite(2,0,c.x,c.y):this.drawSprite(1,0,c.x,c.y);for(c=a=0;c<WORLD.otherPlayers.length;c++)b=WORLD.otherPlayers[c],this.drawSprite(1,2,b.x,b.y),b.x==YOU.x&&b.y==YOU.y&&a++;for(c=0;c<WORLD.otherObjs.length;c++){b=WORLD.otherObjs[c];for(var e=d=0;e<this.openedDoors;e++){var f=this.openedDoors[e].split("|"),
h=parseInt(f[0]);f=parseInt(f[1]);h==b.x&&f==b.y&&(d=1)}switch(b.char){case WORLD.TILES.wood_block:dynamicTile(this,WORLD.TILES.wood_block,0,7,b.x,b.y,!1,!0);break;case WORLD.TILES.scrap_block:dynamicTile(this,WORLD.TILES.scrap_block,4,7,b.x,b.y,!1,!0);break;case WORLD.TILES.steel_block:dynamicTile(this.WORLD.TILES.steel_block,8,7,b.x,b.y,!1,!0);break;case WORLD.TILES.anchor:this.drawSprite(7,1,b.x,b.y);break;case WORLD.TILES.small_chest:this.drawSprite(8,1,b.x,b.y);break;case WORLD.TILES.large_chest:this.drawSprite(9,
1,b.x,b.y);break;case WORLD.TILES.wood_door:this.drawSprite(0+d,8,b.x,b.y);break;case WORLD.TILES.scrap_door:this.drawSprite(4+d,8,b.x,b.y);break;case WORLD.TILES.steel_door:this.drawSprite(8+d,8,b.x,b.y);break;case WORLD.TILES.sign_block:this.drawSprite(10,1,b.x,b.y);case WORLD.TILES.city:this.drawSprite(4,1,x,y);case WORLD.TILES.house:this.drawSprite(3,1,x,y);break;case "@":this.drawSprite(4,2,b.x,b.y);break;default:this.drawSprite(0,0,b.x,b.y)}}2<a?this.drawSprite(3,2,YOU.x,YOU.y):1<a?this.drawSprite(2,
2,YOU.x,YOU.y):this.drawSprite(0,2,YOU.x,YOU.y);this.drawSprite(0,1,0,0);this.render()};function generateIndices(a){for(var c=new Uint16Array(a),b=0,d=0;b<a;b+=6,d+=4)c[b]=d,c[b+1]=d+1,c[b+2]=d+2,c[b+3]=d+1,c[b+4]=d+3,c[b+5]=d+2;return c}var TILE_ENUM={n:1,e:2,s:4,w:8};
function dynamicTile(a,c,b,d,e,f,h,g){g=void 0===g?!1:g;var k=0;if(void 0===h?0:h)h=perlinInt(e,f),WORLD.deriveTile(e,f+1)==c&&perlinInt(e,f+1)<h+1?k|=TILE_ENUM.n:null,WORLD.deriveTile(e+1,f)==c&&perlinInt(e+1,f)<h+1?k|=TILE_ENUM.e:null,WORLD.deriveTile(e,f-1)==c&&perlinInt(e,f-1)<h+1?k|=TILE_ENUM.s:null,WORLD.deriveTile(e-1,f)==c&&perlinInt(e-1,f)<h+1?k|=TILE_ENUM.w:null;else if(g)for(h=0;h<WORLD.otherObjs;h++)g=WORLD.otherObjs[h],g.char==c&&(e==g.x&&f+1==g.y?k|=TILE_ENUM.n:null,e+1==g.x&&f==g.y?
k|=TILE_ENUM.e:null,e==g.x&&f-1==g.y?k|=TILE_ENUM.s:null,e-1==g.x&&f==g.y?k|=TILE_ENUM.w:null);else WORLD.deriveTile(e,f+1)==c?k|=TILE_ENUM.n:null,WORLD.deriveTile(e+1,f)==c?k|=TILE_ENUM.e:null,WORLD.deriveTile(e,f-1)==c?k|=TILE_ENUM.s:null,WORLD.deriveTile(e-1,f)==c?k|=TILE_ENUM.w:null;switch(k){case TILE_ENUM.e|TILE_ENUM.s:a.drawSprite(b,d,e,f);break;case TILE_ENUM.e|TILE_ENUM.s|TILE_ENUM.w:a.drawSprite(b+1,d,e,f);break;case TILE_ENUM.s|TILE_ENUM.w:a.drawSprite(b+2,d,e,f);break;case TILE_ENUM.s:a.drawSprite(b+
3,d,e,f);break;case TILE_ENUM.n|TILE_ENUM.e|TILE_ENUM.s:a.drawSprite(b,d+1,e,f);break;case TILE_ENUM.n|TILE_ENUM.e|TILE_ENUM.s|TILE_ENUM.w:a.drawSprite(b+1,d+1,e,f);break;case TILE_ENUM.n|TILE_ENUM.s|TILE_ENUM.w:a.drawSprite(b+2,d+1,e,f);break;case TILE_ENUM.n|TILE_ENUM.s:a.drawSprite(b+3,d+1,e,f);break;case TILE_ENUM.n|TILE_ENUM.e:a.drawSprite(b,d+2,e,f);break;case TILE_ENUM.n|TILE_ENUM.e|TILE_ENUM.w:a.drawSprite(b+1,d+2,e,f);break;case TILE_ENUM.n|TILE_ENUM.w:a.drawSprite(b+2,d+2,e,f);break;case TILE_ENUM.n:a.drawSprite(b+
3,d+2,e,f);break;case TILE_ENUM.e:a.drawSprite(b,d+3,e,f);break;case TILE_ENUM.e|TILE_ENUM.w:a.drawSprite(b+1,d+3,e,f);break;case TILE_ENUM.w:a.drawSprite(b+2,d+3,e,f);break;default:a.drawSprite(b+3,d+3,e,f)}}function perlinInt(a,c){var b=WORLD.getPerlin(a,c);a=WORLD.getPerlin(a,c+5500,1E4)-WORLD.getPerlin(a,c,25);b=Math.floor(30*b);.1>a&&b++;return b}
var vertexShaderSource="#version 300 es\n    in vec4 a_position;\n    in vec2 a_texcoord;\n\n    out vec2 v_texcoord;\n\n    void main()\n    {\n        gl_Position = a_position;\n        v_texcoord = a_texcoord;\n    }\n",fragmentShaderSource="#version 300 es\n    precision mediump float;\n\n    in vec2 v_texcoord;\n    uniform sampler2D u_texture;\n\n    out vec4 color;\n\n    void main()\n    {\n        color = texture(u_texture, v_texcoord);\n    }\n",stylesSource="\n#world-box{position:relative;}\ncanvas{position:absolute;top:0;right:0;left:0;bottom:0;}\n";
function main(){new Renderer("https://i.ibb.co/NVM1Gxr/spritesheet.png")}main();var Shader=function(a){this.webGl=a;this.compiled=!1;this.attributes=[];this.uniforms=[]};Shader.prototype.compile=function(a,c){this.vertexShaderId=this.createShader(this.webGl.VERTEX_SHADER,a);this.fragmentShaderId=this.createShader(this.webGl.FRAGMENT_SHADER,c);this.vertexShaderId&&this.fragmentShaderId&&(this.programId=this.createProgram(),null!=this.programId&&(this.compiled=!0))};
Shader.prototype.createShader=function(a,c){a=this.webGl.createShader(a);this.webGl.shaderSource(a,c);this.webGl.compileShader(a);return this.webGl.getShaderParameter(a,this.webGl.COMPILE_STATUS)?a:(console.log("failed to compile shader"),console.log(this.webGl.getShaderInfoLog(a)),this.webGl.deleteShader(a),null)};
Shader.prototype.createProgram=function(){var a=this.webGl.createProgram();this.webGl.attachShader(a,this.vertexShaderId);this.webGl.attachShader(a,this.fragmentShaderId);this.webGl.linkProgram(a);if(!this.webGl.getProgramParameter(a,this.webGl.LINK_STATUS))return console.log("failed to link program"),console.log(this.webGl.getProgramInfoLog(a)),this.webGl.deleteProgram(a),null;this.webGl.deleteShader(this.vertexShaderId);this.webGl.deleteShader(this.fragmentShaderId);return a};
Shader.prototype.getUniform=function(a){this.uniforms[a]||(this.uniforms[a]=this.webGl.getUniformLocation(this.programId,a));return this.uniforms[a]||null};Shader.prototype.getAttribute=function(a){this.attributes[a]||(this.attributes[a]=this.webGl.getAttribLocation(this.programId,a));return this.attributes[a]||null};