var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,f){if(b){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var d=a[f];d in c||(c[d]={});c=c[d]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Math.sign",function(a){return a?a:function(a){a=Number(a);return 0===a||isNaN(a)?a:0<a?1:-1}},"es6","es3");
var Renderer=function(a){var b=this;this.width;this.height;this.currentPosition=0;this.scale=2;this.offsetY=this.offsetX=0;this.keydown=!1;this.vbo;this.vao;this.ebo;this.maxQuads=16384;this.maxVertices;this.vertices;this.indices;this.indexPtr=this.vertexPtr=this.spriteCount=0;this.focusedOnPlayer=!0;this.lastTime;this.d_t;this.running=!1;this.spritesheet=new Image;this.spritesheet.crossOrigin="";this.spritesheet.src=a;this.spritesheet.addEventListener("load",function(){b.running?b.setTexture(b.spritesheet):
(b.running=!0,b.merge(),b.initWebGl(),b.initEvents(),b.start(),requestAnimationFrame(function(a){return b.update(a)}))})};Renderer.prototype.merge=function(){var a=this,b=document.createElement("style");b.styleSheet?b.styleSheet.cssText=stylesSource:b.appendChild(document.createTextNode(stylesSource));document.getElementsByTagName("head")[0].appendChild(b);this.openedDoors=[];var c=ENGINE.applyData;ENGINE.applyData=function(b,d){c(b,d);a.openedDoors=b.doors}};
Renderer.prototype.initWebGl=function(){this.canvas=document.createElement("canvas");this.canvas.id="canvas";this.parent=document.getElementsByClassName("mid-screencontainer")[0];this.parent.insertBefore(this.canvas,null);this.webGl=this.canvas.getContext("webgl2");null===this.webGl?alert("sorry bub, but you should start using a modern browser..."):(this.resize(),this.shader=new Shader(this.webGl),this.shader.compile(vertexShaderSource,fragmentShaderSource),this.shader.compiled?(this.setTexture(this.spritesheet),
this.maxVertices=16*this.maxQuads,this.vertices=new Float32Array(this.maxVertices),this.vbo=this.webGl.createBuffer(),this.webGl.bindBuffer(this.webGl.ARRAY_BUFFER,this.vbo),this.webGl.bufferData(this.webGl.ARRAY_BUFFER,this.vertices,this.webGl.DYNAMIC_DRAW),this.indices=generateIndices(6*this.maxQuads),this.ebo=this.webGl.createBuffer(),this.webGl.bindBuffer(this.webGl.ELEMENT_ARRAY_BUFFER,this.ebo),this.webGl.bufferData(this.webGl.ELEMENT_ARRAY_BUFFER,this.indices,this.webGl.DYNAMIC_DRAW),this.webGl.useProgram(this.shader.programId),
this.webGl.enableVertexAttribArray(this.shader.getAttribute("a_position")),this.webGl.bindBuffer(this.webGl.ARRAY_BUFFER,this.vbo),this.webGl.vertexAttribPointer(this.shader.getAttribute("a_position"),2,this.webGl.FLOAT,!1,16,0),this.webGl.enableVertexAttribArray(this.shader.getAttribute("a_texcoord")),this.webGl.vertexAttribPointer(this.shader.getAttribute("a_texcoord"),2,this.webGl.FLOAT,!1,16,8),this.webGl.bindBuffer(this.webGl.ELEMENT_ARRAY_BUFFER,this.ebo),this.webGl.uniform1i(this.shader.getUniform("u_texture"),
0)):alert("uh oh, spaghetti ohs. i suck at writing shaders"))};
Renderer.prototype.setTexture=function(a){this.textureId||(this.textureId=this.webGl.createTexture(),this.webGl.bindTexture(this.webGl.TEXTURE_2D,this.textureId),this.webGl.texParameteri(this.webGl.TEXTURE_2D,this.webGl.TEXTURE_MIN_FILTER,this.webGl.NEAREST_MIPMAP_NEAREST),this.webGl.texParameteri(this.webGl.TEXTURE_2D,this.webGl.TEXTURE_MIN_FILTER,this.webGl.NEAREST),this.webGl.texParameteri(this.webGl.TEXTURE_2D,this.webGl.TEXTURE_MAG_FILTER,this.webGl.NEAREST),this.webGl.blendFunc(this.webGl.SRC_ALPHA,
this.webGl.ONE_MINUS_SRC_ALPHA),this.webGl.enable(this.webGl.BLEND));this.webGl.texImage2D(this.webGl.TEXTURE_2D,0,this.webGl.RGBA,this.webGl.RGBA,this.webGl.UNSIGNED_BYTE,a)};
Renderer.prototype.initEvents=function(){var a=this;this.canvas.addEventListener("mousedown",function(b){return a.mouseupdown(b)});addEventListener("mouseup",function(b){return a.mouseupdown(b)});addEventListener("mousemove",function(b){return a.mousemove(b)});addEventListener("resize",function(b){return a.resize(b)});this.canvas.addEventListener("wheel",function(b){return a.scroll(b)});this.imgHTML=document.createElement("input");this.imgHTML.style.display="none";this.imgHTML.type="file";this.imgHTML.accept=
"image/*";document.getElementsByTagName("body")[0].appendChild(this.imgHTML);this.imgHTML.addEventListener("change",function(b){b=b.target.files[0];a.reader||(a.reader=new FileReader,a.reader.onload=function(b){a.spritesheet.src=b.target.result});a.reader.readAsDataURL(b)});addEventListener("keydown",function(b){" "==b.key?(b.preventDefault(),a.focusedOnPlayer=!0,a.curX=YOU.x,a.curY=YOU.y,a.scale=2):"t"==b.key&&(a.imgHTML.style.display="block",a.imgHTML.click(),a.imgHTML.style.display="none")})};
Renderer.prototype.start=function(){this.moveCamera(YOU.x,YOU.y);this.curX=YOU.x;this.curY=YOU.y};Renderer.prototype.update=function(a){var b=this;this.d_t=this.lastTime?a-this.lastTime:0;this.lastTime=a;this.focusedOnPlayer&&(a=this.d_t/500,this.curX=Math.abs(YOU.x-this.curX)<a?YOU.x:this.curX-(this.curX-YOU.x)*a,this.curY=Math.abs(YOU.y-this.curY)<a?YOU.y:this.curY-(this.curY-YOU.y)*a,this.moveCamera(this.curX,this.curY));this.drawScene();requestAnimationFrame(function(a){return b.update(a)})};
Renderer.prototype.moveCamera=function(a,b){this.offsetX=12*a*this.scale-this.canvas.width/2+6*this.scale;this.offsetY=12*b*this.scale-this.canvas.height/2+6*this.scale};
Renderer.prototype.scroll=function(a){a.preventDefault();var b=this.canvas.getBoundingClientRect(),c=(a.clientX-b.left+this.offsetX)/this.scale,f=(b.bottom-a.clientY+this.offsetY)/this.scale;this.scale+=Math.sign(a.deltaY)/10*this.scale;.00001>this.scale&&(this.scale=.00001);var d=(a.clientX-b.left+this.offsetX)/this.scale;this.offsetY+=(f-(b.bottom-a.clientY+this.offsetY)/this.scale)*this.scale;this.offsetX+=(c-d)*this.scale};
Renderer.prototype.mouseupdown=function(a){a.preventDefault();0==a.button&&a.target==this.canvas&&("mousedown"===a.type?(this.focusedOnPlayer=!1,this.keydown=!0):this.keydown=!1)};Renderer.prototype.mousemove=function(a){this.keydown&&(this.offsetX-=a.movementX,this.offsetY+=a.movementY)};Renderer.prototype.resize=function(){this.width=this.parent.clientWidth;this.height=this.parent.clientHeight;this.canvas.width=this.width;this.canvas.height=this.height;this.webGl.viewport(0,0,this.width,this.height)};
Renderer.prototype.drawSprite=function(a,b,c,f){this.vertexPtr>=this.maxVertices&&this.render();var d=c*this.scale,e=f*this.scale;c=(c+this.detail)*this.scale;f=(f+this.detail)*this.scale;var g=a+.01,h=b+.99;a+=.99;b+=.01;this.addAttribute(this.normalizePosition(d,e));this.addAttribute(this.normalizeTexture(g,h));this.addAttribute(this.normalizePosition(d,f));this.addAttribute(this.normalizeTexture(g,b));this.addAttribute(this.normalizePosition(c,e));this.addAttribute(this.normalizeTexture(a,h));
this.addAttribute(this.normalizePosition(c,f));this.addAttribute(this.normalizeTexture(a,b));this.indexPtr+=6};Renderer.prototype.render=function(){this.webGl.bufferSubData(this.webGl.ARRAY_BUFFER,0,this.vertices,0,this.vertexPtr);this.webGl.drawElements(this.webGl.TRIANGLES,this.indexPtr,this.webGl.UNSIGNED_SHORT,0);this.vertexPtr=this.indexPtr=0};Renderer.prototype.addAttribute=function(a){this.vertices[this.vertexPtr++]=a.x;this.vertices[this.vertexPtr++]=a.y};
Renderer.prototype.normalizePosition=function(a,b){return{x:Math.floor(12*a-this.offsetX)/this.width*2-1,y:Math.floor(12*b-this.offsetY)/this.height*2-1}};Renderer.prototype.normalizeTexture=function(a,b){return{x:16*a/this.spritesheet.width,y:16*b/this.spritesheet.height}};
Renderer.prototype.drawScene=function(){this.webGl.clearColor(0,0,0,0);this.webGl.clear(this.webGl.COLOR_BUFFER_BIT);this.detail=Math.ceil(1/this.scale);var a=Math.ceil(this.canvas.height/12/this.scale/2)+this.detail+1,b=Math.ceil(this.canvas.width/12/this.scale/2)+this.detail+1,c=YOU.x,f=YOU.y;this.focusedOnPlayer||(c=Math.floor(this.offsetX/12/this.scale)+b,f=Math.floor(this.offsetY/12/this.scale)+a);c=Math.floor(c/this.detail)*this.detail;f=Math.floor(f/this.detail)*this.detail;for(var d=c-b;d<
c+b;d+=this.detail)for(var e=f-a;e<f+a;e+=this.detail)switch(WORLD.deriveTile(d,e)){case WORLD.TILES.sand:this.drawSprite(1,0,d,e);break;case WORLD.TILES.grass:dynamicTile(this,WORLD.TILES.grass,4,3,d,e);break;case WORLD.TILES.tree:.57<WORLD.getPerlin(d,e+5500,1E4)?this.drawSprite(2,1,d,e):this.drawSprite(1,1,d,e);break;case WORLD.TILES.mountain:dynamicTile(this,WORLD.TILES.mountain,0,3,d,e,!0);break;case WORLD.TILES.swamp:dynamicTile(this,WORLD.TILES.swamp,12,3,d,e);break;case WORLD.TILES.forest:dynamicTile(this,
WORLD.TILES.forest,8,3,d,e);break;case WORLD.TILES.water:dynamicTile(this,WORLD.TILES.water,16,3,d,e);break;case WORLD.TILES.island:this.drawSprite(2,0,d,e);break;case WORLD.TILES.worldedge:dynamicTile(this,WORLD.TILES.worldedge,20,3,d,e);break;case WORLD.TILES.house:this.drawSprite(3,1,d,e);break;case WORLD.TILES.city:this.drawSprite(4,1,d,e);break;case WORLD.TILES.startbox:this.drawSprite(5,1,d,e);break;default:this.drawSprite(0,0,d,e)}for(a=0;a<WORLD.otherStumps.length;a++)b=WORLD.otherStumps[a],
.57<WORLD.getPerlin(b.x,b.y+5500,1E4)?this.drawSprite(2,0,b.x,b.y):this.drawSprite(1,0,b.x,b.y);for(b=a=0;b<WORLD.otherPlayers.length;b++)c=WORLD.otherPlayers[b],this.drawSprite(1,2,c.x,c.y),c.x==YOU.x&&c.y==YOU.y&&a++;for(b=0;b<WORLD.otherObjs.length;b++){c=WORLD.otherObjs[b];for(d=f=0;d<this.openedDoors;d++){var g=this.openedDoors[d].split("|");e=parseInt(g[0]);g=parseInt(g[1]);e==c.x&&g==c.y&&(f=1)}switch(c.char){case WORLD.TILES.wood_block:this.dynamicTile(this,WORLD.TILES.wood_block,0,7,c.x,
c.y,!1,!0);break;case WORLD.TILES.scrap_block:this.dynamicTile(this,WORLD.TILES.scrap_block,4,7,c.x,c.y,!1,!0);break;case WORLD.TILES.steel_block:this.dynamicTile(this.WORLD.TILES.steel_block,8,7,c.x,c.y,!1,!0);break;case WORLD.TILES.anchor:this.drawSprite(7,1,c.x,c.y);break;case WORLD.TILES.small_chest:this.drawSprite(8,1,c.x,c.y);break;case WORLD.TILES.large_chest:this.drawSprite(9,1,c.x,c.y);break;case WORLD.TILES.wood_door:this.drawSprite(0+f,8,c.x,c.y);break;case WORLD.TILES.scrap_door:this.drawSprite(4+
f,8,c.x,c.y);break;case WORLD.TILES.steel_door:this.drawSprite(8+f,8,c.x,c.y);break;case WORLD.TILES.sign_block:this.drawSprite(10,1,c.x,c.y);case WORLD.TILES.city:case WORLD.TILES.city:break;default:this.drawSprite(0,0,c.x,c.y)}}2<a?this.drawSprite(3,2,YOU.x,YOU.y):1<a?this.drawSprite(2,2,YOU.x,YOU.y):this.drawSprite(0,2,YOU.x,YOU.y);this.drawSprite(0,1,0,0);this.render()};
function generateIndices(a){for(var b=new Uint16Array(a),c=0,f=0;c<a;c+=6,f+=4)b[c]=f,b[c+1]=f+1,b[c+2]=f+2,b[c+3]=f+1,b[c+4]=f+3,b[c+5]=f+2;return b}var TILE_ENUM={n:1,e:2,s:4,w:8};
function dynamicTile(a,b,c,f,d,e,g,h){h=void 0===h?!1:h;var l=0,k=a.detail;if(void 0===g?0:g)g=perlinInt(d,e),WORLD.deriveTile(d,e+k)==b&&perlinInt(d,e+k)<g+1?l|=TILE_ENUM.n:null,WORLD.deriveTile(d+k,e)==b&&perlinInt(d+k,e)<g+1?l|=TILE_ENUM.e:null,WORLD.deriveTile(d,e-k)==b&&perlinInt(d,e-k)<g+1?l|=TILE_ENUM.s:null,WORLD.deriveTile(d-k,e)==b&&perlinInt(d-k,e)<g+1?l|=TILE_ENUM.w:null;else if(h)for(g=0;g<WORLD.otherObjs;g++)h=WORLD.otherObjs[g],h.char==b&&(d==h.x&&e+k==h.y?l|=TILE_ENUM.n:null,d+k==
h.x&&e==h.y?l|=TILE_ENUM.e:null,d==h.x&&e-k==h.y?l|=TILE_ENUM.s:null,d-k==h.x&&e==h.y?l|=TILE_ENUM.w:null);else WORLD.deriveTile(d,e+k)==b?l|=TILE_ENUM.n:null,WORLD.deriveTile(d+k,e)==b?l|=TILE_ENUM.e:null,WORLD.deriveTile(d,e-k)==b?l|=TILE_ENUM.s:null,WORLD.deriveTile(d-k,e)==b?l|=TILE_ENUM.w:null;switch(l){case TILE_ENUM.e|TILE_ENUM.s:a.drawSprite(c,f,d,e);break;case TILE_ENUM.e|TILE_ENUM.s|TILE_ENUM.w:a.drawSprite(c+1,f,d,e);break;case TILE_ENUM.s|TILE_ENUM.w:a.drawSprite(c+2,f,d,e);break;case TILE_ENUM.s:a.drawSprite(c+
3,f,d,e);break;case TILE_ENUM.n|TILE_ENUM.e|TILE_ENUM.s:a.drawSprite(c,f+1,d,e);break;case TILE_ENUM.n|TILE_ENUM.e|TILE_ENUM.s|TILE_ENUM.w:a.drawSprite(c+1,f+1,d,e);break;case TILE_ENUM.n|TILE_ENUM.s|TILE_ENUM.w:a.drawSprite(c+2,f+1,d,e);break;case TILE_ENUM.n|TILE_ENUM.s:a.drawSprite(c+3,f+1,d,e);break;case TILE_ENUM.n|TILE_ENUM.e:a.drawSprite(c,f+2,d,e);break;case TILE_ENUM.n|TILE_ENUM.e|TILE_ENUM.w:a.drawSprite(c+1,f+2,d,e);break;case TILE_ENUM.n|TILE_ENUM.w:a.drawSprite(c+2,f+2,d,e);break;case TILE_ENUM.n:a.drawSprite(c+
3,f+2,d,e);break;case TILE_ENUM.e:a.drawSprite(c,f+3,d,e);break;case TILE_ENUM.e|TILE_ENUM.w:a.drawSprite(c+1,f+3,d,e);break;case TILE_ENUM.w:a.drawSprite(c+2,f+3,d,e);break;default:a.drawSprite(c+3,f+3,d,e)}}function perlinInt(a,b){var c=WORLD.getPerlin(a,b);a=WORLD.getPerlin(a,b+5500,1E4)-WORLD.getPerlin(a,b,25);c=Math.floor(30*c);.1>a&&c++;return c}
var vertexShaderSource="#version 300 es\n    in vec4 a_position;\n    in vec2 a_texcoord;\n\n    out vec2 v_texcoord;\n\n    void main()\n    {\n        gl_Position = a_position;\n        v_texcoord = a_texcoord;\n    }\n",fragmentShaderSource="#version 300 es\n    precision mediump float;\n\n    in vec2 v_texcoord;\n    uniform sampler2D u_texture;\n\n    out vec4 color;\n\n    void main()\n    {\n        color = texture(u_texture, v_texcoord);\n    }\n",stylesSource="\n#game-content{display:flex !important;}\ndiv.mid-screencontainer{width:70% !important;position:relative;}\ndiv.side-screencontainer{width:15% !important;}\n#arrow-box{width:114px !important;height:114px !important;}\ndiv.bottom-box-left-menu{height:98px !important;}\ndiv.arrows{width:30px !important;height:30px !important;}\ndiv.arrows > img{width:30px;}\n#bottom-box{z-index:2;position:relative;width:auto !important;}\n#world-time, #world-position{position:relative; z-index:2}\n#hotbar-box{z-index:2;position:relative;width:max-content !important;}\n#canvas{z-index:1;position:absolute;left:0;right:0;top:0;bottom:0;}\n";
function main(){new Renderer("https://i.ibb.co/4Kxjp1X/spritesheet.png")}main();var Shader=function(a){this.webGl=a;this.compiled=!1;this.attributes=[];this.uniforms=[]};Shader.prototype.compile=function(a,b){this.vertexShaderId=this.createShader(this.webGl.VERTEX_SHADER,a);this.fragmentShaderId=this.createShader(this.webGl.FRAGMENT_SHADER,b);this.vertexShaderId&&this.fragmentShaderId&&(this.programId=this.createProgram(),null!=this.programId&&(this.compiled=!0))};
Shader.prototype.createShader=function(a,b){a=this.webGl.createShader(a);this.webGl.shaderSource(a,b);this.webGl.compileShader(a);return this.webGl.getShaderParameter(a,this.webGl.COMPILE_STATUS)?a:(console.log("failed to compile shader"),console.log(this.webGl.getShaderInfoLog(a)),this.webGl.deleteShader(a),null)};
Shader.prototype.createProgram=function(){var a=this.webGl.createProgram();this.webGl.attachShader(a,this.vertexShaderId);this.webGl.attachShader(a,this.fragmentShaderId);this.webGl.linkProgram(a);if(!this.webGl.getProgramParameter(a,this.webGl.LINK_STATUS))return console.log("failed to link program"),console.log(this.webGl.getProgramInfoLog(a)),this.webGl.deleteProgram(a),null;this.webGl.deleteShader(this.vertexShaderId);this.webGl.deleteShader(this.fragmentShaderId);return a};
Shader.prototype.getUniform=function(a){this.uniforms[a]||(this.uniforms[a]=this.webGl.getUniformLocation(this.programId,a));return this.uniforms[a]||null};Shader.prototype.getAttribute=function(a){this.attributes[a]||(this.attributes[a]=this.webGl.getAttribLocation(this.programId,a));return this.attributes[a]||null};